apiVersion: v1
kind: Namespace
metadata:
  name: kube-middleware
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-v2ray
  labels:
    app: proxy-v2ray
  namespace: kube-middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-v2ray
  template:
    metadata:
      labels:
        app: proxy-v2ray
    spec:
      containers:
        - name: proxy-v2ray
          env:
            - name: V2RAY_VMESS_PORT
              value: "10086"
            - name: V2RAY_CLIENT_ID
              value: "b831381d-6324-4d53-ad4f-8cda48b30811"
          image: zhiqiangwang/proxy:v2ray
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
          ports:
            - containerPort: 10086
              name: tcp-10086
              protocol: TCP